#############################################################################
# Makefile for building: 8x8
# Generated by qmake (2.01a) (Qt 4.7.0) on: dom may 6 14:56:30 2012
# Project:  8x8.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile 8x8.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Ifltk -IGUI -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Box.cpp \
		ColorChange.cpp \
		FltkMain.cpp \
		FltkPrueba1.cpp \
		FltkTabletView.cpp \
		Game.cpp \
		Graphic.cpp \
		MoMain.cpp \
		MoPrueba1.cpp \
		MoTabletView.cpp \
		PosChange.cpp \
		Prueba1.cpp \
		SizeChange.cpp \
		TabletController.cpp \
		TabletModel.cpp \
		TabletView.cpp \
		backup/Blocks.cpp \
		backup/dobleClick.cpp \
		backup/Main.cpp \
		backup/oldBlocks.cpp \
		backup/Window.cpp \
		fltk/Animation.cpp \
		fltk/Blocks.cpp \
		fltk/Box.cpp \
		fltk/dobleClick.cpp \
		fltk/FLMain.cpp \
		fltk/FLTKSurface.cpp \
		fltk/FltkTabletController.cpp \
		fltk/ideas.cpp \
		fltk/Main.cpp \
		fltk/MoTabletController.cpp \
		fltk/oldBlocks.cpp \
		fltk/SpaceAnimation.cpp \
		fltk/Surface.cpp \
		fltk/Tablet.cpp \
		fltk/TabletController.cpp \
		fltk/TabletView.cpp \
		fltk/Window.cpp \
		GUI/Graph.cpp \
		GUI/GUI.cpp \
		GUI/Simple_window.cpp \
		GUI/Window.cpp \
		txt/Main.cpp \
		fltk/backup/chapter.13.10-2.cpp \
		fltk/backup/FLMain.cpp \
		fltk/backup/ideas.cpp \
		fltk/backup/Surface.cpp \
		fltk/backup/GUI/Graph.cpp \
		fltk/backup/GUI/GUI.cpp \
		fltk/backup/GUI/Simple_window.cpp \
		fltk/backup/GUI/Window.cpp 
OBJECTS       = Box.o \
		ColorChange.o \
		FltkMain.o \
		FltkPrueba1.o \
		FltkTabletView.o \
		Game.o \
		Graphic.o \
		MoMain.o \
		MoPrueba1.o \
		MoTabletView.o \
		PosChange.o \
		Prueba1.o \
		SizeChange.o \
		TabletController.o \
		TabletModel.o \
		TabletView.o \
		Blocks.o \
		dobleClick.o \
		Main.o \
		oldBlocks.o \
		Window.o \
		Animation.o \
		Blocks.o \
		Box.o \
		dobleClick.o \
		FLMain.o \
		FLTKSurface.o \
		FltkTabletController.o \
		ideas.o \
		Main.o \
		MoTabletController.o \
		oldBlocks.o \
		SpaceAnimation.o \
		Surface.o \
		Tablet.o \
		TabletController.o \
		TabletView.o \
		Window.o \
		Graph.o \
		GUI.o \
		Simple_window.o \
		Window.o \
		Main.o \
		chapter.13.10-2.o \
		FLMain.o \
		ideas.o \
		Surface.o \
		Graph.o \
		GUI.o \
		Simple_window.o \
		Window.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		8x8.pro
QMAKE_TARGET  = 8x8
DESTDIR       = 
TARGET        = 8x8

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: 8x8.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile 8x8.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -o Makefile 8x8.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/8x81.0.0 || $(MKDIR) .tmp/8x81.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/8x81.0.0/ && $(COPY_FILE) --parents Area.h Box.h Color.h ColorChange.h FltkTabletView.h Graphics.h MoTabletView.h Point.h PosChange.h Prueba1.h Rect.h SizeChange.h TabletController.h TabletModel.h TabletView.h backup/Program.h fltk/Animation.h fltk/Box.h fltk/FLTKSurface.h fltk/FltkTabletController.h fltk/MoTabletController.h fltk/Program.h fltk/SpaceAnimation.h fltk/Surface.h fltk/Tablet.h fltk/TabletController.h fltk/TabletView.h fltk/TextSurface.h GUI/Graph.h GUI/GUI.h GUI/Point.h GUI/Simple_window.h GUI/std_lib_facilities.h GUI/Window.h fltk/backup/Surface.h fltk/backup/TextSurface.h fltk/backup/GUI/Graph.h fltk/backup/GUI/GUI.h fltk/backup/GUI/Point.h fltk/backup/GUI/Simple_window.h fltk/backup/GUI/std_lib_facilities.h fltk/backup/GUI/Window.h .tmp/8x81.0.0/ && $(COPY_FILE) --parents Box.cpp ColorChange.cpp FltkMain.cpp FltkPrueba1.cpp FltkTabletView.cpp Game.cpp Graphic.cpp MoMain.cpp MoPrueba1.cpp MoTabletView.cpp PosChange.cpp Prueba1.cpp SizeChange.cpp TabletController.cpp TabletModel.cpp TabletView.cpp backup/Blocks.cpp backup/dobleClick.cpp backup/Main.cpp backup/oldBlocks.cpp backup/Window.cpp fltk/Animation.cpp fltk/Blocks.cpp fltk/Box.cpp fltk/dobleClick.cpp fltk/FLMain.cpp fltk/FLTKSurface.cpp fltk/FltkTabletController.cpp fltk/ideas.cpp fltk/Main.cpp fltk/MoTabletController.cpp fltk/oldBlocks.cpp fltk/SpaceAnimation.cpp fltk/Surface.cpp fltk/Tablet.cpp fltk/TabletController.cpp fltk/TabletView.cpp fltk/Window.cpp GUI/Graph.cpp GUI/GUI.cpp GUI/Simple_window.cpp GUI/Window.cpp txt/Main.cpp fltk/backup/chapter.13.10-2.cpp fltk/backup/FLMain.cpp fltk/backup/ideas.cpp fltk/backup/Surface.cpp fltk/backup/GUI/Graph.cpp fltk/backup/GUI/GUI.cpp fltk/backup/GUI/Simple_window.cpp fltk/backup/GUI/Window.cpp .tmp/8x81.0.0/ && (cd `dirname .tmp/8x81.0.0` && $(TAR) 8x81.0.0.tar 8x81.0.0 && $(COMPRESS) 8x81.0.0.tar) && $(MOVE) `dirname .tmp/8x81.0.0`/8x81.0.0.tar.gz . && $(DEL_FILE) -r .tmp/8x81.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

Box.o: Box.cpp Box.h \
		Rect.h \
		Color.h \
		ColorChange.h \
		PosChange.h \
		SizeChange.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Box.o Box.cpp

ColorChange.o: ColorChange.cpp ColorChange.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ColorChange.o ColorChange.cpp

FltkMain.o: FltkMain.cpp FltkTabletView.h \
		TabletView.h \
		Prueba1.h \
		TabletController.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FltkMain.o FltkMain.cpp

FltkPrueba1.o: FltkPrueba1.cpp FltkTabletView.h \
		TabletView.h \
		Prueba1.h \
		TabletController.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FltkPrueba1.o FltkPrueba1.cpp

FltkTabletView.o: FltkTabletView.cpp FltkTabletView.h \
		TabletView.h \
		TabletController.h \
		TabletModel.h \
		Box.h \
		Rect.h \
		Color.h \
		ColorChange.h \
		PosChange.h \
		SizeChange.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FltkTabletView.o FltkTabletView.cpp

Game.o: Game.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Game.o Game.cpp

Graphic.o: Graphic.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Graphic.o Graphic.cpp

MoMain.o: MoMain.cpp fltk/MoTabletController.h \
		MoTabletView.h \
		TabletModel.h \
		Box.h \
		Rect.h \
		Color.h \
		ColorChange.h \
		PosChange.h \
		SizeChange.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MoMain.o MoMain.cpp

MoPrueba1.o: MoPrueba1.cpp MoTabletView.h \
		TabletModel.h \
		Box.h \
		Rect.h \
		Color.h \
		ColorChange.h \
		PosChange.h \
		SizeChange.h \
		Prueba1.h \
		TabletController.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MoPrueba1.o MoPrueba1.cpp

MoTabletView.o: MoTabletView.cpp MoTabletView.h \
		TabletModel.h \
		Box.h \
		Rect.h \
		Color.h \
		ColorChange.h \
		PosChange.h \
		SizeChange.h \
		fltk/MoTabletController.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MoTabletView.o MoTabletView.cpp

PosChange.o: PosChange.cpp PosChange.h \
		Rect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PosChange.o PosChange.cpp

Prueba1.o: Prueba1.cpp Prueba1.h \
		TabletController.h \
		TabletModel.h \
		Box.h \
		Rect.h \
		Color.h \
		ColorChange.h \
		PosChange.h \
		SizeChange.h \
		TabletView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Prueba1.o Prueba1.cpp

SizeChange.o: SizeChange.cpp SizeChange.h \
		Rect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SizeChange.o SizeChange.cpp

TabletController.o: TabletController.cpp TabletController.h \
		TabletView.h \
		TabletModel.h \
		Box.h \
		Rect.h \
		Color.h \
		ColorChange.h \
		PosChange.h \
		SizeChange.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TabletController.o TabletController.cpp

TabletModel.o: TabletModel.cpp TabletModel.h \
		Box.h \
		Rect.h \
		Color.h \
		ColorChange.h \
		PosChange.h \
		SizeChange.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TabletModel.o TabletModel.cpp

TabletView.o: TabletView.cpp TabletView.h \
		TabletModel.h \
		Box.h \
		Rect.h \
		Color.h \
		ColorChange.h \
		PosChange.h \
		SizeChange.h \
		TabletController.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TabletView.o TabletView.cpp

Blocks.o: backup/Blocks.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Blocks.o backup/Blocks.cpp

dobleClick.o: backup/dobleClick.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dobleClick.o backup/dobleClick.cpp

Main.o: backup/Main.cpp TabletController.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Main.o backup/Main.cpp

oldBlocks.o: backup/oldBlocks.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o oldBlocks.o backup/oldBlocks.cpp

Window.o: backup/Window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Window.o backup/Window.cpp

Animation.o: fltk/Animation.cpp fltk/Animation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Animation.o fltk/Animation.cpp

Blocks.o: fltk/Blocks.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Blocks.o fltk/Blocks.cpp

Box.o: fltk/Box.cpp fltk/Box.h \
		fltk/Animation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Box.o fltk/Box.cpp

dobleClick.o: fltk/dobleClick.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dobleClick.o fltk/dobleClick.cpp

FLMain.o: fltk/FLMain.cpp fltk/Tablet.h \
		fltk/Box.h \
		fltk/Animation.h \
		fltk/TextSurface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FLMain.o fltk/FLMain.cpp

FLTKSurface.o: fltk/FLTKSurface.cpp fltk/FLTKSurface.h \
		fltk/Tablet.h \
		fltk/Box.h \
		fltk/Animation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FLTKSurface.o fltk/FLTKSurface.cpp

FltkTabletController.o: fltk/FltkTabletController.cpp fltk/FltkTabletController.h \
		fltk/TabletView.h \
		fltk/Tablet.h \
		fltk/Box.h \
		fltk/Animation.h \
		fltk/TabletController.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FltkTabletController.o fltk/FltkTabletController.cpp

ideas.o: fltk/ideas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ideas.o fltk/ideas.cpp

Main.o: fltk/Main.cpp fltk/Tablet.h \
		fltk/Box.h \
		fltk/Animation.h \
		fltk/FLTKSurface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Main.o fltk/Main.cpp

MoTabletController.o: fltk/MoTabletController.cpp fltk/MoTabletController.h \
		MoTabletView.h \
		TabletModel.h \
		Box.h \
		Rect.h \
		Color.h \
		ColorChange.h \
		PosChange.h \
		SizeChange.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MoTabletController.o fltk/MoTabletController.cpp

oldBlocks.o: fltk/oldBlocks.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o oldBlocks.o fltk/oldBlocks.cpp

SpaceAnimation.o: fltk/SpaceAnimation.cpp fltk/SpaceAnimation.h \
		Rect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SpaceAnimation.o fltk/SpaceAnimation.cpp

Surface.o: fltk/Surface.cpp fltk/Surface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Surface.o fltk/Surface.cpp

Tablet.o: fltk/Tablet.cpp fltk/Tablet.h \
		fltk/Box.h \
		fltk/Animation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Tablet.o fltk/Tablet.cpp

TabletController.o: fltk/TabletController.cpp fltk/TabletController.h \
		fltk/TabletView.h \
		fltk/Tablet.h \
		fltk/Box.h \
		fltk/Animation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TabletController.o fltk/TabletController.cpp

TabletView.o: fltk/TabletView.cpp fltk/TabletView.h \
		fltk/Tablet.h \
		fltk/Box.h \
		fltk/Animation.h \
		fltk/TabletController.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TabletView.o fltk/TabletView.cpp

Window.o: fltk/Window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Window.o fltk/Window.cpp

Graph.o: GUI/Graph.cpp GUI/Graph.h \
		GUI/Point.h \
		GUI/std_lib_facilities.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Graph.o GUI/Graph.cpp

GUI.o: GUI/GUI.cpp GUI/GUI.h \
		GUI/Window.h \
		GUI/Point.h \
		GUI/Graph.h \
		GUI/std_lib_facilities.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GUI.o GUI/GUI.cpp

Simple_window.o: GUI/Simple_window.cpp GUI/Simple_window.h \
		GUI/GUI.h \
		GUI/Window.h \
		GUI/Point.h \
		GUI/Graph.h \
		GUI/std_lib_facilities.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Simple_window.o GUI/Simple_window.cpp

Window.o: GUI/Window.cpp GUI/Window.h \
		GUI/Point.h \
		GUI/Graph.h \
		GUI/std_lib_facilities.h \
		GUI/GUI.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Window.o GUI/Window.cpp

Main.o: txt/Main.cpp fltk/Tablet.h \
		fltk/Box.h \
		fltk/Animation.h \
		Box.h \
		Rect.h \
		Color.h \
		ColorChange.h \
		PosChange.h \
		SizeChange.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Main.o txt/Main.cpp

chapter.13.10-2.o: fltk/backup/chapter.13.10-2.cpp GUI/Simple_window.h \
		GUI/GUI.h \
		GUI/Window.h \
		GUI/Point.h \
		GUI/Graph.h \
		GUI/std_lib_facilities.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chapter.13.10-2.o fltk/backup/chapter.13.10-2.cpp

FLMain.o: fltk/backup/FLMain.cpp fltk/Tablet.h \
		fltk/Box.h \
		fltk/Animation.h \
		Box.h \
		Rect.h \
		Color.h \
		ColorChange.h \
		PosChange.h \
		SizeChange.h \
		fltk/backup/TextSurface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FLMain.o fltk/backup/FLMain.cpp

ideas.o: fltk/backup/ideas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ideas.o fltk/backup/ideas.cpp

Surface.o: fltk/backup/Surface.cpp fltk/backup/Surface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Surface.o fltk/backup/Surface.cpp

Graph.o: fltk/backup/GUI/Graph.cpp fltk/backup/GUI/Graph.h \
		fltk/backup/GUI/Point.h \
		fltk/backup/GUI/std_lib_facilities.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Graph.o fltk/backup/GUI/Graph.cpp

GUI.o: fltk/backup/GUI/GUI.cpp fltk/backup/GUI/GUI.h \
		fltk/backup/GUI/Window.h \
		fltk/backup/GUI/Point.h \
		fltk/backup/GUI/Graph.h \
		fltk/backup/GUI/std_lib_facilities.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GUI.o fltk/backup/GUI/GUI.cpp

Simple_window.o: fltk/backup/GUI/Simple_window.cpp fltk/backup/GUI/Simple_window.h \
		fltk/backup/GUI/GUI.h \
		fltk/backup/GUI/Window.h \
		fltk/backup/GUI/Point.h \
		fltk/backup/GUI/Graph.h \
		fltk/backup/GUI/std_lib_facilities.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Simple_window.o fltk/backup/GUI/Simple_window.cpp

Window.o: fltk/backup/GUI/Window.cpp fltk/backup/GUI/Window.h \
		fltk/backup/GUI/Point.h \
		fltk/backup/GUI/Graph.h \
		fltk/backup/GUI/std_lib_facilities.h \
		fltk/backup/GUI/GUI.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Window.o fltk/backup/GUI/Window.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

